[package]
name = "rust-asynchronous-grpc-server-iot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "iot-server"
src = "src/server.rs"

[dependencies]
