// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/iot_manifest.AuthService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, "/iot_manifest.AuthService/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) Auth(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (UnimplementedAuthServiceServer) VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_manifest.AuthService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_manifest.AuthService/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyToken(ctx, req.(*VerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iot_manifest.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _AuthService_Auth_Handler,
		},
		{
			MethodName: "VerifyToken",
			Handler:    _AuthService_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iot_manifest.proto",
}

// IoTServiceClient is the client API for IoTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IoTServiceClient interface {
	GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (IoTService_GetDevicesClient, error)
	RecordStatistics(ctx context.Context, in *Device, opts ...grpc.CallOption) (*RecordStatisticsResponse, error)
	SendCommand(ctx context.Context, opts ...grpc.CallOption) (IoTService_SendCommandClient, error)
	AddAccess(ctx context.Context, opts ...grpc.CallOption) (IoTService_AddAccessClient, error)
	RemoveAccess(ctx context.Context, opts ...grpc.CallOption) (IoTService_RemoveAccessClient, error)
}

type ioTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIoTServiceClient(cc grpc.ClientConnInterface) IoTServiceClient {
	return &ioTServiceClient{cc}
}

func (c *ioTServiceClient) GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (IoTService_GetDevicesClient, error) {
	stream, err := c.cc.NewStream(ctx, &IoTService_ServiceDesc.Streams[0], "/iot_manifest.IoTService/GetDevices", opts...)
	if err != nil {
		return nil, err
	}
	x := &ioTServiceGetDevicesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IoTService_GetDevicesClient interface {
	Recv() (*Device, error)
	grpc.ClientStream
}

type ioTServiceGetDevicesClient struct {
	grpc.ClientStream
}

func (x *ioTServiceGetDevicesClient) Recv() (*Device, error) {
	m := new(Device)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ioTServiceClient) RecordStatistics(ctx context.Context, in *Device, opts ...grpc.CallOption) (*RecordStatisticsResponse, error) {
	out := new(RecordStatisticsResponse)
	err := c.cc.Invoke(ctx, "/iot_manifest.IoTService/RecordStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTServiceClient) SendCommand(ctx context.Context, opts ...grpc.CallOption) (IoTService_SendCommandClient, error) {
	stream, err := c.cc.NewStream(ctx, &IoTService_ServiceDesc.Streams[1], "/iot_manifest.IoTService/SendCommand", opts...)
	if err != nil {
		return nil, err
	}
	x := &ioTServiceSendCommandClient{stream}
	return x, nil
}

type IoTService_SendCommandClient interface {
	Send(*DeviceEvent) error
	Recv() (*Device, error)
	grpc.ClientStream
}

type ioTServiceSendCommandClient struct {
	grpc.ClientStream
}

func (x *ioTServiceSendCommandClient) Send(m *DeviceEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ioTServiceSendCommandClient) Recv() (*Device, error) {
	m := new(Device)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ioTServiceClient) AddAccess(ctx context.Context, opts ...grpc.CallOption) (IoTService_AddAccessClient, error) {
	stream, err := c.cc.NewStream(ctx, &IoTService_ServiceDesc.Streams[2], "/iot_manifest.IoTService/AddAccess", opts...)
	if err != nil {
		return nil, err
	}
	x := &ioTServiceAddAccessClient{stream}
	return x, nil
}

type IoTService_AddAccessClient interface {
	Send(*AddAccessRequest) error
	Recv() (*AddAccessResponse, error)
	grpc.ClientStream
}

type ioTServiceAddAccessClient struct {
	grpc.ClientStream
}

func (x *ioTServiceAddAccessClient) Send(m *AddAccessRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ioTServiceAddAccessClient) Recv() (*AddAccessResponse, error) {
	m := new(AddAccessResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ioTServiceClient) RemoveAccess(ctx context.Context, opts ...grpc.CallOption) (IoTService_RemoveAccessClient, error) {
	stream, err := c.cc.NewStream(ctx, &IoTService_ServiceDesc.Streams[3], "/iot_manifest.IoTService/RemoveAccess", opts...)
	if err != nil {
		return nil, err
	}
	x := &ioTServiceRemoveAccessClient{stream}
	return x, nil
}

type IoTService_RemoveAccessClient interface {
	Send(*RemoveAccessRequest) error
	Recv() (*RemoveAccessResponse, error)
	grpc.ClientStream
}

type ioTServiceRemoveAccessClient struct {
	grpc.ClientStream
}

func (x *ioTServiceRemoveAccessClient) Send(m *RemoveAccessRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ioTServiceRemoveAccessClient) Recv() (*RemoveAccessResponse, error) {
	m := new(RemoveAccessResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IoTServiceServer is the server API for IoTService service.
// All implementations must embed UnimplementedIoTServiceServer
// for forward compatibility
type IoTServiceServer interface {
	GetDevices(*GetDevicesRequest, IoTService_GetDevicesServer) error
	RecordStatistics(context.Context, *Device) (*RecordStatisticsResponse, error)
	SendCommand(IoTService_SendCommandServer) error
	AddAccess(IoTService_AddAccessServer) error
	RemoveAccess(IoTService_RemoveAccessServer) error
	mustEmbedUnimplementedIoTServiceServer()
}

// UnimplementedIoTServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIoTServiceServer struct {
}

func (UnimplementedIoTServiceServer) GetDevices(*GetDevicesRequest, IoTService_GetDevicesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDevices not implemented")
}
func (UnimplementedIoTServiceServer) RecordStatistics(context.Context, *Device) (*RecordStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordStatistics not implemented")
}
func (UnimplementedIoTServiceServer) SendCommand(IoTService_SendCommandServer) error {
	return status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedIoTServiceServer) AddAccess(IoTService_AddAccessServer) error {
	return status.Errorf(codes.Unimplemented, "method AddAccess not implemented")
}
func (UnimplementedIoTServiceServer) RemoveAccess(IoTService_RemoveAccessServer) error {
	return status.Errorf(codes.Unimplemented, "method RemoveAccess not implemented")
}
func (UnimplementedIoTServiceServer) mustEmbedUnimplementedIoTServiceServer() {}

// UnsafeIoTServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IoTServiceServer will
// result in compilation errors.
type UnsafeIoTServiceServer interface {
	mustEmbedUnimplementedIoTServiceServer()
}

func RegisterIoTServiceServer(s grpc.ServiceRegistrar, srv IoTServiceServer) {
	s.RegisterService(&IoTService_ServiceDesc, srv)
}

func _IoTService_GetDevices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDevicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IoTServiceServer).GetDevices(m, &ioTServiceGetDevicesServer{stream})
}

type IoTService_GetDevicesServer interface {
	Send(*Device) error
	grpc.ServerStream
}

type ioTServiceGetDevicesServer struct {
	grpc.ServerStream
}

func (x *ioTServiceGetDevicesServer) Send(m *Device) error {
	return x.ServerStream.SendMsg(m)
}

func _IoTService_RecordStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTServiceServer).RecordStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_manifest.IoTService/RecordStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTServiceServer).RecordStatistics(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoTService_SendCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IoTServiceServer).SendCommand(&ioTServiceSendCommandServer{stream})
}

type IoTService_SendCommandServer interface {
	Send(*Device) error
	Recv() (*DeviceEvent, error)
	grpc.ServerStream
}

type ioTServiceSendCommandServer struct {
	grpc.ServerStream
}

func (x *ioTServiceSendCommandServer) Send(m *Device) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ioTServiceSendCommandServer) Recv() (*DeviceEvent, error) {
	m := new(DeviceEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _IoTService_AddAccess_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IoTServiceServer).AddAccess(&ioTServiceAddAccessServer{stream})
}

type IoTService_AddAccessServer interface {
	Send(*AddAccessResponse) error
	Recv() (*AddAccessRequest, error)
	grpc.ServerStream
}

type ioTServiceAddAccessServer struct {
	grpc.ServerStream
}

func (x *ioTServiceAddAccessServer) Send(m *AddAccessResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ioTServiceAddAccessServer) Recv() (*AddAccessRequest, error) {
	m := new(AddAccessRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _IoTService_RemoveAccess_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IoTServiceServer).RemoveAccess(&ioTServiceRemoveAccessServer{stream})
}

type IoTService_RemoveAccessServer interface {
	Send(*RemoveAccessResponse) error
	Recv() (*RemoveAccessRequest, error)
	grpc.ServerStream
}

type ioTServiceRemoveAccessServer struct {
	grpc.ServerStream
}

func (x *ioTServiceRemoveAccessServer) Send(m *RemoveAccessResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ioTServiceRemoveAccessServer) Recv() (*RemoveAccessRequest, error) {
	m := new(RemoveAccessRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IoTService_ServiceDesc is the grpc.ServiceDesc for IoTService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IoTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iot_manifest.IoTService",
	HandlerType: (*IoTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordStatistics",
			Handler:    _IoTService_RecordStatistics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDevices",
			Handler:       _IoTService_GetDevices_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendCommand",
			Handler:       _IoTService_SendCommand_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AddAccess",
			Handler:       _IoTService_AddAccess_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RemoveAccess",
			Handler:       _IoTService_RemoveAccess_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "iot_manifest.proto",
}
